### ISSUE TITLE
presentation-render.rb:19:in `open': no implicit conversion of URI::HTTP into String (TypeError)

### ISSUE THREAD

**Issue by spider-x** [danielpetri1/bbb-recording-exporter#12]
Hello, it is showing me this error. Can you tell me what to do? Thank you.
`presentation-render.rb:19:in `open': no implicit conversion of URI::HTTP into String (TypeError)
        from presentation-render.rb:19:in `block in download'
        from presentation-render.rb:18:in `open'
        from presentation-render.rb:18:in `download'
        from presentation-render.rb:25:in `block in <main>'
        from presentation-render.rb:24:in `each'
        from presentation-render.rb:24:in `<main>'`

**Comment by danielpetri1** [comment]
Are you using the version of the client that was pushed yersterday?

**Comment by danielpetri1** [comment]
Can you try with the reference recording? You need the " " around the link

**Comment by spider-x** [comment]
I had old version. Now with new version it shows 404 error. I have tried to enter the url both with and without " " . When i put the link to the web browser it is working. Just  files /shapes.svg and /video/webcams.mp4 are not on the server (404 error)
`
C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:364:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:741:in `buffer_open'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:212:in `block in open_loop'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:210:in `catch'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:210:in `open_loop'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:151:in `open_uri'
        from C:/Ruby30-x64/lib/ruby/3.0.0/open-uri.rb:721:in `open'
        from download_client.rb:22:in `block in download'
        from download_client.rb:21:in `open'
        from download_client.rb:21:in `download'
        from download_client.rb:32:in `block in <main>'
        from download_client.rb:31:in `each'
        from download_client.rb:31:in `<main>'
`

**Comment by spider-x** [comment]
It seems that the webcams.mp4 file is webcams.webm on our server.

**Comment by hostbbb** [comment]
edit  presentations.yml to  have -mp4, and new recordings  will have .mp4 generated.  needed for working on MAC/IOS devices.

**Comment by spider-x** [comment]
> edit presentations.yml to have -mp4, and new recordings will have .mp4 generated. needed for working on MAC/IOS devices.

I know this, but server administrator don’t want allow mp4 format. He is saying that mp4 and webm together consumes too much disk space.

**Comment by hostbbb** [comment]
only need -mp4,  if you need to support apple/ios devices this should be the setting... (webm not needed)

you can also use ffmpeg cmd line changes and make daniels script also work with .webm

**Comment by danielpetri1** [comment]
If you replace every instance of .mp4 with .webm, the script should still work.

Did you manage to download the files? 

Kind regards,
Daniel

**Comment by spider-x** [comment]
I have changed every ".mp4" to ".webm" in the *.rb files . Now  it shows new error `
[AVFilterGraph @ 0000012efc694740] No such filter: 'scale=w=1280:h=720:force_original_aspect_ratio=1,pad=1280:720:-1:-1:white'
Error initializing complex filters.
Invalid argument
`

**Comment by danielpetri1** [comment]
I don't know what could be causing this error. Does the whiteboard render with this command?

ffmpeg -f concat -i whiteboard_timestamps -c:v libvpx-vp9 -b:v 2500k -pix_fmt yuva420p -metadata:s:v:0 alpha_mode=\"1\" -vsync vfr -auto-alt-ref 0 -y whiteboard.webm
