### ISSUE TITLE
arrangement of webcams

### ISSUE THREAD

**Issue by yvikt** [danielpetri1/bbb-recording-exporter#26]
Hi, is it possible to arrange cameras in column, but not in grid, like in original bbb recordings?
As I understand, it happens here
https://github.com/danielpetri1/bbb-recording-exporter/blob/46c0625e19445eff5a0a370da5609cf505e1acd4/render_whiteboard.rb#L238
Thank you.👍

**Comment by danielpetri1** [comment]
Hi, the script works by taking the merged webcam files big blue button provides, not the raw data. So currently that is not possible.

**Comment by yvikt** [comment]
Oh, l understand. Thank you.
