### ISSUE TITLE
Feature request: add quality options

### ISSUE THREAD

**Issue by felcaetano** [danielpetri1/bbb-recording-exporter#28]
Add parameters to the quality of the final video: resolution, FPS, bitrate and so on.
Disk space is really an issue for us, so would be interesting to tune these options to make the final file the smallest possible while maintaining some quality. 

On a side note: congratulations for this amazing job. This has been a long request feature for us, your solution is simple, yet efficient and elegant.

**Comment by danielpetri1** [comment]
Great idea. Fortunately FFmpeg makes tweaking these kinds of parameters easy.

Thank you for these kind words, I am surprised by the warm embrace the BBB community has given me so far =)

**Comment by danielpetri1** [comment]
The code now has a video quality option.
