### ISSUE TITLE
Feature request: Notify when the process is done

### ISSUE THREAD

**Issue by felcaetano** [danielpetri1/bbb-recording-exporter#29]
I believe there are two main ways to achieve this.

1- Using the 'meta_bbb-recording-ready-url' just like described in 
https://github.com/bigbluebutton/bigbluebutton/blob/fe403dfd05fe38ca50eb0ef319c22c2cc62f2c43/record-and-playback/core/scripts/post_publish/post_publish_recording_ready_callback.rb
So, to user needs to send the callback URL as a parameter the moment the meeting is created.
The message sent needs to be a little different from the default so we could distinguish which event we are getting. Otherwise the user would get a duplicated notification. 
This looks like the best solution and a great part of it is already done.

2- Using bbb-webhooks. For this you'd would need to publish an event on Redis server and let the bbb-webhooks deal with it. I'm not really sure if this would really work right away because the weebhooks **probably** don't notify unknown events. But I think it's worth mentioning because if you plan to merge this project, would be cool to add this event on the bbb-webhooks too.

**Comment by felcaetano** [comment]
Maybe this issue doesn't make sense anymore. Previously the scripts' filename started with "render_*" so everything used to run after the "post_publish_recording_ready_callback.rb".
Now it starts with "export" so one could use the native BBB callback if they feel like it.

**Comment by danielpetri1** [comment]
@hostbbb shared the following `mp4CallBack.sh` script to achieve this with me:

```
#!/bin/bash
# Call back - needs meetingID as shell argument $1
callBack=$(cat /var/bigbluebutton/published/presentation/$1/metadata.xml | grep mp4-recording-ready-url |sed 's/    <mp4-recording-ready-url>//g' | sed 's|</mp4-recording-ready-url>||' | sed 's/\&amp;/&/')
echo "$callBack"
/usr/bin/curl -d "meetingId=$1" -X POST $callBack
#CURL='/usr/bin/curl'
#CURLARGS="-f -s -S -k"
# The result can be stored in a variable
#raw="$CURL $CURLARGS $callBack&meetingId=$1"
#echo $raw
````
