### ISSUE TITLE
How and where to locate the files for deletion 

### ISSUE THREAD

**Issue by deepaksinghkr** [danielpetri1/bbb-recording-exporter#31]
Hi Daniel,

I am using the server side script for mp4 generation and wants to delete the meeting.mp4 files as well as any other raw files related to the meeting id. This is just to make the server space free once the mp4 file is downloaded for offline use.
Can you pls let me know where and how to delete all the recording related files ? and if it is possible to delete it by Delete API of BBB.

Thanks,
Deepak

**Comment by hostbbb** [comment]
the delete api, moves the published presentation folder /var/bigbluebutton/deleted, you use cron to delete these every so often.

currently this program adds the meeting.mp4 in the standard html5 recording folder.   So deleting will delete both the html5 and .mp4 versions of the recordings.

if you look in the presentation folder you can also see the temp objects the the exporter created as well should be easy to delete those eventually.   good for debugging now as this is new, and some new whiteboard features like eraser etc will require more dev.

**Comment by danielpetri1** [comment]
Hi @deepaksinghkr,
Since the latest version, the scratch files are automatically deleted once rendering completes.

Kind regards,
Daniel
