### ISSUE TITLE
How to modify greenligt file for download?

### ISSUE THREAD

**Issue by blu-IT** [danielpetri1/bbb-recording-exporter#33]
Hi,

where do I find the file  

`app/views/admins/components/_server_recording_row.html.erb`

mentioned here

https://github.com/danielpetri1/greenlight/commit/72c2165e4a504aa40e116a83864de36dea540b65#diff-85f840dbcf9f4c943b923268c312f12c61c4700ddc140ebcf3d4c29cf736c55a

for a integration of a download-button in greenlight?

I installed bbb with docker install script...

Thanks!

**Comment by SaeedFazlollahzadeh** [comment]
Hello,

It is located at `/usr/src/app/` inside the greenlight, so the full path is `/usr/src/app/app/views/admins/components/_server_recording_row.html.erb`

**Comment by blu-IT** [comment]
Thanks!

**Comment by gschwed** [comment]
**ad download button in Greenlight:**
There is no need to modify Greenlight. The button will appear automatically if there is a folder in bigbluebutton/published/mp4 with the mp4 file inside plus a well formatted metadata.xml.
Greenlight always searches the folders for existing metadata.xml. 
In this file you can also define the name of the button for Greenlight.
![Clipboard02](https://user-images.githubusercontent.com/13130832/130780570-5ec0415e-9078-4a7b-89f7-a963925d6f7e.gif)

This is my suggestion for an improvement of the really very good recording exporter to automatically generate the metadata.xml.

**Comment by gschwed** [comment]
@danielpetri1 
Please contact me directly for futher cooperation!
g.schwed at think-modular.com

We (my company www.think-modular.com) do a lot with BBB and want to improve this wonderful software as well as your helpful plugin.

Greetings from Wien

**Comment by danielpetri1** [comment]
Hi @gschwed,
Thanks for this very promising solution.
Could you please share the metadata XML of the translation test you did above?
I would then integrate your solution into the exporting script.

Regards,
Daniel

**Comment by danielpetri1** [comment]
Nevermind, just saw that changing the playback link suffices using the same file.

Thank you very much!

**Comment by danielpetri1** [comment]
Hi @gschwed,
The latest version of the code automatically adds these buttons to Greenlight.

**Comment by gschwed** [comment]
@danielpetri1,
Many thanks! :-)
