### ISSUE TITLE
doubts on how to update to the new bbb-recording-exporter version

### ISSUE THREAD

**Issue by jpmirandaa** [danielpetri1/bbb-recording-exporter#34]
Hi,

1. Is it necessary to compile FFmpg with `--enable-librsvg` and `--enable-libx264`? Does Bigbluebutton not have it installed from the install.sh script?
2. Having installed the previous version of bbb-recording-exporter, is it necessary to delete the files  `render_chat.rb`, `render_cursor.rb`, and `render_whiteboard.rb` in `/usr/local/bigbluebutton/core/scripts/post_publish`

I have already installed loofah on my server but these doubts have arisen to me.

Thank you, Daniel.
JP

**Comment by danielpetri1** [comment]
Hi @jpmirandaa,

1. BBB's FFmpeg is already compiled with `--enable-librsvg` and `--enable-libx264`. No further actions are needed.
2. Yes, please remove the old export scripts, and replace them with export_presentation.rb only.

**Comment by danielpetri1** [comment]
Documentation has been updated.
