### ISSUE TITLE
Dragging Lines, shapes and text graphical issues

### ISSUE THREAD

**Issue by shad00m** [danielpetri1/bbb-recording-exporter#36]
When dragging lines or shapes on a slide the shapes are drawn multiple times, see this video as an example:
https://user-images.githubusercontent.com/9115740/126910281-0ccb62ec-2795-4149-acc1-f7ace4b99b54.mp4

Also when removing one written character it doesn't remove it which results in multiple characters in one space, see this image:
![Screenshot 2021-07-25 205936](https://user-images.githubusercontent.com/9115740/126910286-2079457a-1bc4-438a-8596-cd442b0c40e0.png)

bbb 2.3 used latest client-side branch

**Comment by danielpetri1** [comment]
Hi @shad00m.
do the problems get resolved when you set `REMOVE_REDUNDANT_SHAPES` to true in  `export_presentation.rb`?
