### ISSUE TITLE
Client side how to

### ISSUE THREAD

**Issue by alis-maroc** [danielpetri1/bbb-recording-exporter#37]
Hi
Thanks for the solution, i make server exporter but client side how to do please ?
Where put download_client.rb ?

Thanks again

**Comment by danielpetri1** [comment]
Hi, I'm not sure I understand your question - you can just leave `download_client.rb` in the directory it comes in and then run it from there.

**Comment by alis-maroc** [comment]
Thanks for your response...
If i have understand, i have to download directory to my server and run file ?
But where to download client side files ?
Excuse me but i dont understand how to do with client side files...

Thanks again

**Comment by danielpetri1** [comment]
The client-side code is meant for people that want to download a recording from the webplayer directly, even if the server does not offer this functionality. Since you seem to have access to a server, you can add the script to it and then this functionality will be offered by default.

**Comment by alis-maroc** [comment]
Ah OK
I wonder if this client side is for users to show download button or some like this to facilitate downloading from playback file..
I guess they have to write adresse of mp4 file to downlaod it..

**Comment by danielpetri1** [comment]
To add a download button to Greenlight, you can make [these](https://github.com/danielpetri1/greenlight/commit/72c2165e4a504aa40e116a83864de36dea540b65) changes in Greenlight.

I'm aware this is not that easy to follow - in a few week's time I'll write proper step-by-step instructions.

Cheers

**Comment by alis-maroc** [comment]
Thanks very much...
