### ISSUE TITLE
What is download_client.rb and meeting_id.mp4 in meeting_id directories

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [danielpetri1/bbb-recording-exporter#38]
Hello,

First of all I should say thanks for this work which is highly appreciated:)

My question is

1. what is the role of file `download_client.rb` and is that necessary to place it somewhere?
I mean I cloned this git repo in my server in a path like `/root/`, and only moved the files `export_presentation.rb` and `lib/interval_tree.rb` to mentioned directories with executive rights, and since the day I did it's making `mp4` files in `/var/bigbluebutton/published/presentation/meeting_id/meeting.mp4` with no issue.
Is that all? Or I should do any other things?
2. I also see many of these when I run this command:
```
find . -name '*.mp4' -exec ls -lh {} \;
-rw-r--r-- 1 bigbluebutton bigbluebutton 210M Aug 12 09:45 ./5b47d382b32ad48b12492577000a574c154e0465-1628745881813/meeting.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 185M Aug 12 07:16 ./5b47d382b32ad48b12492577000a574c154e0465-1628745881813/5b47d382b32ad48b12492577000a574c154e0465-1628745881813.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 194M Aug  8 13:00 ./4f3eb13ed936e91b407524f56b6c8b52640c690a-1628406180177/meeting.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 175M Aug  8 10:58 ./4f3eb13ed936e91b407524f56b6c8b52640c690a-1628406180177/4f3eb13ed936e91b407524f56b6c8b52640c690a-1628406180177.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 178M Aug  7 16:10 ./c865285389c7c51b6f12652d054faa21be005222-1628341197035/meeting.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 155M Aug  7 14:40 ./c865285389c7c51b6f12652d054faa21be005222-1628341197035/c865285389c7c51b6f12652d054faa21be005222-1628341197035.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 234M Aug  7 08:36 ./cf10e9a265eb2b487e47f61f4d5d83ab3bf44494-1628314280877/meeting.mp4
-rw-r--r-- 1 bigbluebutton bigbluebutton 207M Aug  7 06:51 ./cf10e9a265eb2b487e47f61f4d5d83ab3bf44494-1628314280877/cf10e9a265eb2b487e47f61f4d5d83ab3bf44494-1628314280877.mp4
```
I do not mean `meeting.mp4` files, but I do mean `/var/bigbluebutton/published/presentation/meeting_id/meeting_id.mp4`. What are these files generated by `bbb-recording-exported` script?

Thanks in advance

**Comment by danielpetri1** [comment]
Hi @SaeedFazlollahzadeh,
The `download_client.rb` file was accidentaly pushed to the main branch. It's only needed for the client-side version of the script. Thanks for mentioning it, it's now gone.

As for the other files, they do not look like something my script would create. Did you try any other exporting scripts like tilmanmoser's bbb-video-download? I believe his script outputs files in that format.

If not, could you please provide some more information, such as BBB's version and so on?
Regards,
Daniel

**Comment by SaeedFazlollahzadeh** [comment]
> Hi @SaeedFazlollahzadeh,
> The `download_client.rb` file was accidentaly pushed to the main branch. It's only needed for the client-side version of the script. Thanks for mentioning it, it's now gone.
> 
> As for the other files, they do not look like something my script would create. Did you try any other exporting scripts like tilmanmoser's bbb-video-download? I believe his script outputs files in that format.
> 
> If not, could you please provide some more information, such as BBB's version and so on?
> Regards,
> Daniel

Hi @danielpetri1 and thanks for the reply,

What is the client-side version? Is that something before existed and it's gone now?

I use tilmanmoser's bbb-video-download in another server, but it only generates `video.mp4` and yours generates `meeting.mp4`. But in this server I only user your script, and I'm not sure why, but I will investigate more for these files.

Regarding information, this server uses BBB 2.2 with Ubuntu 16. More info needed?

Thanks,
Saeed

**Comment by danielpetri1** [comment]
@SaeedFazlollahzadeh the client-side version is on another branch of this repo. It's meant for people that do not have access to a server, such as students wanting to download lectures they attended.

Since you're on Ubuntu 2.2, you need to set `REMOVE_REDUNDANT_SHAPES` to true in the script. Otherwise, the annotations will look weird in your videos.

Regards
Daniel

**Comment by SaeedFazlollahzadeh** [comment]
@danielpetri1 could you please make and example of annotations looking weird? There are many videos and I did not see all of them, but I just saw some of them and I did not find any strange things.

**Comment by danielpetri1** [comment]
@SaeedFazlollahzadeh [Here's](https://user-images.githubusercontent.com/9115740/126910281-0ccb62ec-2795-4149-acc1-f7ace4b99b54.mp4) an example.
