### ISSUE TITLE
Unicode RTL Language writing on whiteboard

### ISSUE THREAD

**Issue by soheilrahsaz** [danielpetri1/bbb-recording-exporter#39]
Hello
First of all, thank you for this beautiful feature.
Everything works fine and is the exact thing as seen on the recording, except for one thing that I have encountered.
Writing Persian on the whiteboard doesn't appear correctly in the final video.

This is the expected result in the BBB presentation link:
![image](https://user-images.githubusercontent.com/38767606/129541602-40524260-2ddd-4e33-8983-634ce98bbae0.png)

This is the result in meeting.mp4:
![image](https://user-images.githubusercontent.com/38767606/129541731-aa4a980f-5f1f-48fc-bec6-09d39d0884f3.png)

Persian is utf8 and RTL. Maybe that's the reason.
Thanks in Advance

**Comment by danielpetri1** [comment]
Hi @soheilrahsaz,
Can you send me the link of a recording in which this problem occurs so I can try to fix it?
I believe it will be challenging since I don't speak persian.

Does the chat work for you?
Regards
Daniel

**Comment by soheilrahsaz** [comment]
The chat works fine as expected.

This is the link:
https://bbb79.hamkelasi.co/playback/presentation/2.3/72e0ac9f552304448a78a59e9dee75c35500858c-1629096371434
And this is the exported file
https://bbb79.hamkelasi.co/presentation/72e0ac9f552304448a78a59e9dee75c35500858c-1629096371434/meeting.mp4

And this was the string I put into the box:
"سلام من به شما یاران قدیمی"
But any other text should be a good example too. (searching "Sample Persian Text" leads to some good inputs)

Note: BBB whiteboard itself has problems with RTL languages and we suggest that users do not use it. But it does render it correctly.

**Comment by danielpetri1** [comment]
@soheilrahsaz  Perfect, thanks, I'll look into it.

**Comment by danielpetri1** [comment]
Hi @soheilrahsaz,
Is it fixed now?
Cheers

**Comment by soheilrahsaz** [comment]
Thank you for your fast response.
I'm getting this error now:


```
/usr/local/bigbluebutton/core/scripts/post_publish# ./export_presentation.rb -m 72e0ac9f552304448a78a59e9dee75c35500858c-1629096371434
Traceback (most recent call last):
        18: from ./export_presentation.rb:666:in `<main>'
        17: from ./export_presentation.rb:633:in `export_presentation'
        16: from ./export_presentation.rb:177:in `convert_whiteboard_shapes'
        15: from /var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
        14: from /var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
        13: from /var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
        12: from ./export_presentation.rb:221:in `block in convert_whiteboard_shapes'
        11: from /var/lib/gems/2.5.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:94:in `method_missing'
        10: from /var/lib/gems/2.5.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
         9: from /var/lib/gems/2.5.0/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
         8: from ./export_presentation.rb:222:in `block (2 levels) in convert_whiteboard_shapes'
         7: from /var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
         6: from /var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
         5: from /var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
         4: from ./export_presentation.rb:223:in `block (3 levels) in convert_whiteboard_shapes'
         3: from /var/lib/gems/2.5.0/gems/loofah-2.4.0/lib/loofah.rb:44:in `fragment'
         2: from /var/lib/gems/2.5.0/gems/loofah-2.4.0/lib/loofah/html/document_fragment.rb:24:in `parse'
         1: from /var/lib/gems/2.5.0/gems/loofah-2.4.0/lib/loofah/html/document_fragment.rb:24:in `new'
/var/lib/gems/2.5.0/gems/nokogiri-1.11.0-x86_64-linux/lib/nokogiri/html/document_fragment.rb:36:in `initialize': undefined method `strip' for #<Nokogiri::XML::Text:0x0000558f05416858> (NoMethodError)
```

**Comment by danielpetri1** [comment]
Was it with the same input?

**Comment by danielpetri1** [comment]
Does it work when you set line 223 to line = Loofah.fragment(line.to_s).scrub!(:strip).text.unicode_normalize ?

**Comment by soheilrahsaz** [comment]
It appears to be working now, I'll let you know if how's the final result video.

**Comment by danielpetri1** [comment]
Thanks for the quick reply. Interesting, I had the same problem on the server, but trying the code locally worked before. Probably something to do with the Loofah/Nokogiri version.

**Comment by soheilrahsaz** [comment]
It is fixed now.
Thank you!!

**Comment by danielpetri1** [comment]
![Screenshot 2021-08-17 at 11 08 38](https://user-images.githubusercontent.com/33319791/129697663-ca6e3555-ae93-4aed-963c-67e303d06a40.png)
This is how it looks like to me.

**Comment by danielpetri1** [comment]
Great, perfect. I'll push the changes.
