### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by seanvip** [danielpetri1/bbb-recording-exporter#40]
I followed the directions and gave the files the permissions, but I get the following error when attempting to create one mp4 file using the command - ./export_presentation.rb -m 95cd1ac087f121fb0e67269562efa67186ce8a4f-1628822429170 I get the following output:
sh: 1: Syntax error: Unterminated quoted string
An error occurred rendering the video.

**Comment by danielpetri1** [comment]
Hi @seanvip,
Can you please share some more information?

Which version of Ubuntu/BBB are you on? When you  copied the code, did you include the shebang comment in the first line? Does running ruby export_presentation.rb -m 95cd1ac087f121fb0e67269562efa67186ce8a4f-1628822429170 work? What about enclosing the meeting ID in quotes?

I had never seen this before, thanks for mentioning it.
Regards
Daniel

**Comment by soheilrahsaz** [comment]
The chat works fine as expected.

This is the link:
https://bbb79.hamkelasi.co/playback/presentation/2.3/72e0ac9f552304448a78a59e9dee75c35500858c-1629096371434
And this is the exported file
https://bbb79.hamkelasi.co/presentation/72e0ac9f552304448a78a59e9dee75c35500858c-1629096371434/meeting.mp4

And this was the string I put into the box:
"سلام من به شما یاران قدیمی"
But any other text should be a good example too. (searching "Sample Persian Text" leads to some good inputs)

Note: BBB whiteboard itself has problems with RTL languages and we suggest that users do not use it. But it does render it correctly.

**Comment by danielpetri1** [comment]
Perfect, thanks, I'll take a look into it.

**Comment by seanvip** [comment]
Hi Daniel,

I am running Ubuntu 18.04.5, BBB 2.3. The shebang is included. When I got the files, I cloned the whole repo into root and moved the appropriate files. I did double check in vim and the shebang is there. I tried the ruby command and enclosing the meeting id in quotes and still got the same syntax error. I tried the following commands:
ruby export_presentation.rb -m 95cd1ac087f121fb0e67269562efa67186ce8a4f-1628822429170
ruby export_presentation.rb -m "95cd1ac087f121fb0e67269562efa67186ce8a4f-1628822429170"
./export_presentation.rb -m "95cd1ac087f121fb0e67269562efa67186ce8a4f-1628822429170"

They all yielded the same syntax error.

**Comment by danielpetri1** [comment]
Hi Sean, thanks for your reply.
Do other recordings work or is it a problem with this specific one?

**Comment by seanvip** [comment]
Hi Daniel,

I did try the export command with my other meetings and got the same error. I did also try rebuilding all of them (using bbb-record --rebuildall). Unfortunately, when I rebuilt them, it did not encode an mp4 file, so I think it errored out at some point and thus didn't encode them. Since I am on a tight time frame to get all of this stuff up and running, I was forced to remove your encoding system and try to install another. I used manishkatyan's bbb encoder (which does basically the same thing). I did manage to get that one to work and encode mp4 files for our bbb meetings. Thanks for your help though and I wish you all the best on your Thesis project.

Sincerely,

Sean

**Comment by hostbbb** [comment]
@seanvip , would be good if you can provide us a link to the original html5 recording that had the issueto debug this.  @danielpetri1 approach scales very well, and a recording takes about 10-15% the meeting duration to convert.  Where as the approaches use a docker, and chrome screen capture, and requite lots of cpu,  A 2hr class takes 2hrs to convert, since it has to playback in frame grabber.   Daniels approach will take 10-15 minutes. to get the .mp4 for these same.

If we get the url to published recording that had issue, glad to debug.

**Comment by seanvip** [comment]
@hostbbb and @danielpetri1, I have no problem providing the URL to the recording if it helps with your project. The recording is located at - https://christianwaymissions.com/playback/presentation/2.3/2c718a13d4b2a298a98811841bbfddf8f15b7921-1629073441971

However, our server isn't always running since AWS charges us for uptime usage, and we don't need it running all the time. It is typically running from 9 am - 9 pm ChST.

Sincerely,

-Sean

**Comment by danielpetri1** [comment]
Hi Sean,
I tried to access the server many times during the past 2 weeks but never seemed to caught a moment were it was turned on.

I'll keep trying and keep you posted.
Regards,
Daniel

**Comment by danielpetri1** [comment]
Hi @seanvip, 
Now that the server is running, I am getting a 404 - Not Found error. It would be of great help if you could provide another recording.

As a guess to fix your problem - changing `-metadata title='#{meeting_name}'`in the script to `-metadata title=\"#{meeting_name}\"´ could help.
