### ISSUE TITLE
Use a temporary file to meeting.mp4

### ISSUE THREAD

**Issue by felcaetano** [danielpetri1/bbb-recording-exporter#43]
The final file 'meeting.mp4' is being written in its final location while is being processed.
This causes a problem, because if you try to download it before the rendering is over, your server will reply with a HTTP 200, but offer you a broken file.
I believe it should be written on a temporary file first and moved afterwards.

**Comment by danielpetri1** [comment]
Good point - that can be easily fixed by changing all instances of `meeting.mp4` to `tmp.mp4` and then renaming the rendered file after FFmpeg returns true.

**Comment by danielpetri1** [comment]
Thanks for the commit - just saw your fix after implementing it a bit differently, so that chapter marks and captions read in the modified file too.
