### ISSUE TITLE
Change processing time

### ISSUE THREAD

**Issue by msh13792** [danielpetri1/bbb-recording-exporter#48]
hi
how to Change processing time to prepare mp4 files?

**Comment by danielpetri1** [comment]
Hi @msh13792,
Thanks for reaching out. I unfortunately did not understand your question. Could you be a little bit more specific?

Thanks in advance

**Comment by msh13792** [comment]
i should explain when "export_presentation" was working on recorded video to prepare mp4 files that is consume more CPU of my server and it was bad effected on meeting that was opened on server ,i want to know that is a way to change time of processing "export_presentation" automatically for example on 1AM to 8AM of day ?
i hope you can understand exactly what i want.
Thank you for your attention

**Comment by danielpetri1** [comment]
To reduce resource usage you can turn the SVGZ option on in the script and set THREADS to 1.
You could disable the presentation workflow entirely and only let it run from 1AM to 8AM with a cronjob.

**Comment by danielpetri1** [comment]
Reducing the CHAT_CANVAS_SIZE to 320 will also help you out with the CPU load.

**Comment by danielpetri1** [comment]
Closed. Please reopen if the cronjob suggestion did not fullfill your needs or submit it as a feature request.
