### ISSUE TITLE
client side export slides, gets div by 0 in unique function

### ISSUE THREAD

**Issue by hostbbb** [danielpetri1/bbb-recording-exporter#51]
CC", begin=5049.5, end=11482.0, width=1600.0, height="1200">]
Traceback (most recent call last):
        3: from ../../export_slides.rb:261:in `<main>'
        2: from ../../export_slides.rb:254:in `export_pdf'
        1: from ../../export_slides.rb:230:in `unique_slides'
../../export_slides.rb:230:in `/': divided by 0 (ZeroDivisionError)

If i comment out the unique function,  annotates_slides generate fine.

**Comment by danielpetri1** [comment]
Hi, thanks for pointing this out, I've just pushed the fix.

I had forgotten these two lines in the code when debugging, you can either pull the fixed version or remove these two lines:
`p slides`
`i = 1/0`
