### ISSUE TITLE
How to delete the exported files?

### ISSUE THREAD

**Issue by dqcuong93** [danielpetri1/bbb-recording-exporter#53]
Hi,
I would like to know if is there any way to delete these exported files? I have set up BBB to delete files if older than 45 days, so when the file is deleted, what will happen with the exported file? 
And thank you so much for this great work, it saves me a lot of time.

**Comment by danielpetri1** [comment]
Hi @dqcuong93,
I'm not sure if I understand your question, but if you delete the recording, the exported video file/PDF will be deleted too, just  as is the case with the other formats (e.g. presentation) provided by BBB.

**Comment by dqcuong93** [comment]
Sorry for the late reply, I have been busy with Canvas because the whole database is lost, and my client is not happy about that. Thank you for your answer, I understand now.
