### ISSUE TITLE
translation missing: fa_IR.recording.format.Video

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [danielpetri1/bbb-recording-exporter#54]
Hello,

I added script but the `Video` button is in English while my site language is Persian (fa_IR).
When I hover over the button, I see this message:

 > translation missing: fa_IR.recording.format.Video

What string should I add to my language yml file?
Is adding said in https://github.com/danielpetri1/greenlight/commit/72c2165e4a504aa40e116a83864de36dea540b65 enough?

Regards,
Saeed

**Comment by danielpetri1** [comment]
Hi Saaed,
Can you change the contents of line 179 in the code to say "video" instead of "Video"? It should pick up the correct locale without modifying any language file. Can you confirm?

Regards,
Daniel
