### ISSUE TITLE
The playback URL is built with the wrong items

### ISSUE THREAD

**Issue by rabser** [danielpetri1/bbb-recording-exporter#58]
Into the file export_presentation.rb the function that adds the greenlight button is built with the wrong items fixed protocol and wrong hostname.
This code is valid only for a greenlight installation on the same BBB server, but If you connect to BBB with another service (e.g. Moodle), the video URL is broken.

Following is the right code that builds the URL in the metadata.xml correctly, by using the information from bigbluebutton.yml, as the other formats do.

```
def add_greenlight_buttons(metadata)
  bbb_props = YAML::load(File.open('../bigbluebutton.yml'))
  playback_protocol = bbb_props['playback_protocol']
  playback_host = bbb_props['playback_host']

  meeting_id = metadata.xpath('recording/id').inner_text

  metadata.xpath('recording/playback/format').children.first.content = "video"
  metadata.xpath('recording/playback/link').children.first.content = "#{playback_protocol}://#{playback_host}/presentation/#{meeting_id}/meeting.mp4"

  File.open("/var/bigbluebutton/published/video/#{meeting_id}/metadata.xml", "w") do |file|
    file.write(metadata)
  end
end
```

**Comment by rabser** [comment]
My fault, but I'm not able to submit a pull-request, sorry.

**Comment by danielpetri1** [comment]
No problem, just asking since it would list you as a collaborator and thus give proper credits to your work =)

**Comment by rabser** [comment]
Thanks to you for the time spent in trying it!
