### ISSUE TITLE
improvement: dowload_client:  id and servername as parameter

### ISSUE THREAD

**Issue by ka7** [danielpetri1/bbb-recording-exporter#61]
Hi,

i patched (ugly) my version, so I can pass servername and recording-id as parameter. ( argv[0] ... )
´ruby download_client.rb  bbb.example.net  asdfasdfasdf-1234´

with that, its easier if you have multiple recordings on different servers. ( getting videos from a bbb@scale )

with that, scripting gets easier.

for myself, i have a file with 
name-of-recoring;servername;recording_id

and a bit bash-scripting, so its downloading into a new folder named name-of-recording, from servername.

**Comment by danielpetri1** [comment]
Hi, thanks for your suggestion. This has already been fixed in [here](https://github.com/danielpetri1/bbb-recording-exporter/issues/57#issuecomment-947103406). Feel free to submit a PR.
