### ISSUE TITLE
error, when recording contains no desksharing

### ISSUE THREAD

**Issue by ka7** [danielpetri1/bbb-recording-exporter#62]
Hi,

(using download_client)
I had issues, when a recording did not contain a desksharing.mp4 file.
the download_client ended up with errors and a zero-byte desksharing.mp4 file.
had to play around with exluding/including that in the array to get all the files.

export_presentation ended in an error.

This can happen, when you upload slides, start recording, just work with sildes, stop recording; no desktop involved.

as a workaround, i copied a desksharing.mp4 from some other bbb-export - as i assume it will anyway not end up in the resulting video and is just required to make the script happy.

**Comment by danielpetri1** [comment]
You need to remove the deskshare.mp4 file from the files being downloaded in the array. This is mentioned in the README file.
