### ISSUE TITLE
December, 05 version fails rendering a 92 minutes meeting

### ISSUE THREAD

**Issue by jpmirandaa** [danielpetri1/bbb-recording-exporter#66]
Hi, all.
I have recently updated to BBB 2.3.16 and **bbb-recorging-exporting** from October, 07 version to December, 05 version.
I tested to render a one minute meeting and the result was OK.
Yesterday I recorded a 92 minutes meeting and the render was failed. The meeting.mp4 video file did not exist.

I tried to re-render the meeting by **./presentation.rb -m <meeting_id>** code and it was failed again.

I had to downgrade or came back to October, 07 version and re-render the recorded meeting by **./export_presentation.rb -m <meeting_id>** code and this time the render was OK. I have got the meeting.mp4 video file.

Following I put the results of each codes.

Thanks for your comments and best regards.
JP
[December-05 version fails rendering a 92 minutes meeting.txt](https://github.com/danielpetri1/bbb-recording-exporter/files/7729135/December-05.version.fails.rendering.a.92.minutes.meeting.txt)

**Comment by jpmirandaa** [comment]
Hi, again.

I have just upgrade to new December, 16 version. I did not test rendering a new meeting yet but trying to render a meeting recorded by the code ./presentation.rb -m <meeting_id> and I have the same fail result.

Otherwise, putting the files of October, 07 version and rendering by ./export_presentation.rb -m <meeting_id> code the meeting.mp4 video file is OK.

The output of those both versions are practically the same as the text file I uploaded in the opening thread.

Any idea?

**Comment by danielpetri1** [comment]
Hi @jpmirandaa, thanks for the in-depth testing and feedback as usual. I can't determine the cause from the console output -- would you mind sharing the output of `/var/log/bigbluebutton/post_publish.log`?

**Comment by jpmirandaa** [comment]
Don't mention it, Daniel.
Thanks a lot to you for this useful development.

Of course, here are the files.
The file called post_publish.log1.txt belongs to the first thread described.
The post_publish.log2.txt file belongs  to the second thread.

Note that these two files belong to two different BBB servers as well.

Best regards.
JP

[post_publish.log1.txt](https://github.com/danielpetri1/bbb-recording-exporter/files/7739727/post_publish.log1.txt)
[post_publish.log2.txt](https://github.com/danielpetri1/bbb-recording-exporter/files/7739726/post_publish.log2.txt)

**Comment by danielpetri1** [comment]
Hi @jpmirandaa,
So it looks like to me that the videos have been correctly rendered since the paths are listed in the post publish logs. Can you play those files back?

`/var/bigbluebutton/published/presentation/e143527bbdb34a0d74bbe935679191b30733facf-1639513284821/meeting.mp4``

`/var/bigbluebutton/published/presentation/4a91cd7ff05a7b509826d0c9c66279b3bd05ff91-1622579659037/meeting.mp4`

I'm under the impression that it failed when adding the Moodle / Greenlight etc. links in the last step, since the 
`require 'yaml'` in the import list is missing. Adding it should fix that.

(Sorry I can't test it properly, had to upgrade my server to BBB 2.4-rc7 which is not compatible for now)

**Comment by jpmirandaa** [comment]
Daniel,

Perhaps I could not explain the issue better.
Yes. I have those meeting.mp4 files but only after downgrade bbb-recording-exporter to October, 07 version.

Using the two recent December versions I could not manually generate the video files. The render process did not start at all. This is visible in the console output file of my opening post.

Please, read my posts carefully again where I try to explain all things I did to obtain the video files.
Thanks for your comments.

Greetings
JP

**Comment by danielpetri1** [comment]
Hi JP,
Have you tried adding the `-f  presentation` flag when executing the script from the command line? The README had not reflected that change -- my bad.

Greetings

**Comment by jpmirandaa** [comment]
Thank you very much for your answer, Daniel.

I'm afraid I didn't add that flag.
I'll try the latest recent version (Jan 11, 2022) and tell you.

By the way, do you plan to update bbb-recording-exporter to support BBB 2.4?

Greetings.
JP

**Comment by danielpetri1** [comment]
Hi JP,
Thanks for the quick response.
The Trollop gem changed its name to Optimist, which doesn't seem to be installed on your server given the logs.

Can you try installing it with `gem install optimist`? (maybe with sudo if that doesn't work)
Cheers

**Comment by jpmirandaa** [comment]
Hi, Daniel.

I've installed Optimist version of Gem as you suggested.

This time trying to re-render manually a previous presentation using bbb-recording-exporter Jan 11th, 2022 version does not work.
And now trying with Dec 21st, 2021 version does not work either.

Please, look at the attach file of the console outputs.

[Installing optimist and test manually render.txt](https://github.com/danielpetri1/bbb-recording-exporter/files/7866477/Installing.optimist.and.test.manually.render.txt)

Is there some thing could I do to solve the issue?

Greetings
JP

**Comment by jpmirandaa** [comment]
Great, Daniel. Thank you very much.

Now everything works correctly. Both cases, the automatic rendering of the mp4 file after a meeting and the manual re-rendering of a previously recorded presentation. 

By the way, do you plan to update bbb-recording-exporter to support BBB 2.4?

Thanks a lot again and best regards.
JP

**Comment by danielpetri1** [comment]
Hi @jpmirandaa !
Glad to see everything working.
The script does seem to be compatible with BBB 2.4, except that it won't support the poll results / link to shared media in chat. I'm still waiting for an 'official' BBB review of the script before moving on with this.  Sorry I forgot to answer last time.
