### ISSUE TITLE
Congratulations and Thanks

### ISSUE THREAD

**Issue by tecnomaster** [danielpetri1/bbb-recording-exporter#72]
Hi Daniel,

This is just to say THANKS ... I have installed the recorder and it works just fine including all the BBB elements from a recorded session. I have also suscribed to your YouTube channel. Keep going as you have done ... regards from Venezuela and Colombia!.

Daniel (2)

**Comment by danielpetri1** [comment]
Hi @tecnomaster,
Thank you very much for your kind words, much appreciated. Glad to hear it's helping you out!
