### ISSUE TITLE
Error on process for prepare mp4

### ISSUE THREAD

**Issue by msh13792** [danielpetri1/bbb-recording-exporter#76]
hi
when i try this error was occurred
 ruby /usr/local/bigbluebutton/core/scripts/post_publish/export_presentation.rb -m b94066ba8dca436b69f3f386e7c3867006091b3f-1645771898780
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Traceback (most recent call last):
        2: from /usr/local/bigbluebutton/core/scripts/post_publish/export_presentation.rb:4:in `<main>'
        1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- trollop (LoadError)

**Comment by danielpetri1** [comment]
Hi,
Trollop is not a required gem in the script anymore, it was changed to Optimist.
Are you using the latest version of the code?
Kind regards,
Daniel
