### ISSUE TITLE
how to stop the stript?

### ISSUE THREAD

**Issue by Buda9** [danielpetri1/bbb-recording-exporter#80]
Hi there,

First of all, this is great a script! No doubt about that. I'm using it to create mp4 for some videos, however, I don't quite need it for all my videos. To stop the script, can you tell me is it enough to simple delete presentation.rb and interval_tree.rb files?

Kind regards,
Davor

**Comment by danielpetri1** [comment]
Hi @Buda9!
Just deleting the presentation.rb file is enough. In fact, you could try only renaming it to something like presentation-pause.rb while you don't need it, in theory that should work too.

Kind regards and thanks for the nice words
Daniel
