### ISSUE TITLE
What about BBB 2.6

### ISSUE THREAD

**Issue by jpmirandaa** [danielpetri1/bbb-recording-exporter#81]
Hi, Daniel. Hi, all.
Sorry, Daniel. This is just to ask you if is it possible to install this current bbb-recording-exporter version to obtain mp4 files on the new BBB 2.6 as it is so useful on 2.3, 2.4 and 2.5 versions.
Thanks a lot.
JP

**Comment by danielpetri1** [comment]
Hi,
BBB 2.6 will launch with their own implementation of the MP4 exporter since  a lot of the whiteboard changed. You can check the development in [this](https://github.com/bigbluebutton/bbb-presentation-video) repository.
Cheers!

**Comment by jpmirandaa** [comment]
Hi Daniel.
Just to tell you that I installed your development on BBB 2.6.1 and works fine except the annotations on whiteboard. But pdf presentation uploaded, webcams, audio and public chat entries, works well.
Before this I tried with the oficial development (bbb-playback-video) but cannot obtain all of this items in one unique mp4 file as yours does.
Could you please help them to develop a useful only one mp4 file as yours?
Thanks a lot in advance and best regards.
JP

**Comment by hostbbb** [comment]
@jpmirandaa we are looking at taking @danielpetri1 approach in the new 2.6 video format as time allows.   It's not a key priority currently in 2.7 development schedule.  i have a few customers that desire the same.
