### ISSUE TITLE
Compatibility with older BigBlueButton versions

### ISSUE THREAD

**Issue by radasys** [danielpetri1/bbb-recording-exporter#84]
Hi! 

We have to migrate an old BigBlueButton instance that is running version 2.2.

I would like to know if bbb-recording-exporter is compatible with BBB 2.2.

Thanks!

**Comment by danielpetri1** [comment]
Hi @radasys,
I don't know, unfortunately, as I started developing it on 2.3. As AFAIK there were no big changes to the whiteboard between versions, I would expect it to work with a few minor changes. I suggest giving it a shot.

**Comment by radasys** [comment]
I forgot to close this issue. I have been able to export all the recordings without issues in BBB 2.2. Thank you, @danielpetri1 for your hard work with this project!

**Comment by danielpetri1** [comment]
Thanks for the info @radasys, I am glad to hear it works with BBB 2.2!
