### ISSUE TITLE
BBB 2.7 partially working

### ISSUE THREAD

**Issue by davidcanar** [danielpetri1/bbb-recording-exporter#88]
I just installed a new copy of BBB 2.7 and this project. It does generate a .mp4 file but it is missing some things:
1. The web cam video is not showing
2. The drawing board does not have any of the drawings

It does show the slides and the audio works correctly. I haven't tested anything else (polls, video sharing, document sharing, etc)

**Comment by danielpetri1** [comment]
Hi,
BigBlueButton changed its whiteboard starting from 2.6. Possibly refer to https://github.com/bigbluebutton/bbb-presentation-video to obtain a video of the whiteboard area.

Thanks for letting me know that it partially works on 2.7.
